import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider, SignOutButton } from "@clerk/nextjs";
import { SignInButton, SignedIn, SignedOut, UserButton } from "@clerk/nextjs";
import { Button } from "@/components/ui/button";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <header>
            <SignedOut>
              <div className="flex p-24 flex-col justify-center items-center text-xl">
                <SignInButton>
                  <Button>Sign in to continue</Button>
                </SignInButton>
              </div>
            </SignedOut>
            <SignedIn>{children}</SignedIn>
          </header>
        </body>
      </html>
    </ClerkProvider>
  );
}
